spring:
  rabbitmq:
    host: 10.168.4.57
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://10.168.4.222:3306/sdd-showSignal?serverTimezone=UTC
#    url: jdbc:mysql://emsdb/sdd-showSignal?serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
ws-index1: 5000
ws-index2: 5000
ws-index3: 5000
ws-index4: 5000
reconnectionTime: 2000
reconnectionMaxNum: 5000
logoUrl: images/favicon.ico