spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/equipManagerSys?serverTimezone=UTC
    username: root
    password: uihisd
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#权限文档在eolinker的IOT_HUB项目的项目文档
  redis:
    database: 0
    host: lyredisx
    port: 6379
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0
auth:
  url: http://10.6.10.22:8090/auth
  index-page: index
  authorization: false
  authentication: false
minio:
  url: minio-server:9000
  username: scada
  password: scada123
  docBucket: docs

