spring:
  datasource:
    url: jdbc:mysql://10.168.4.222:3306/equipManagerSys?serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 10.168.4.57
    port: 5672
    username: guest
    password: guest
#权限文档在eolinker的IOT_HUB项目的项目文档
  redis:
    database: 0
    host: 10.168.4.11
    port: 6379
    password: scada123
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0
auth:
  url: http://10.168.4.59:8987/auth
  index-page: index
  authorization: false
  authentication: false

minio:
  url: http://10.168.4.223:9000
  username: scada
  password: scada123
  docBucket: docs

